/*
 * File: data.h
 * Created on: 13.10.2017
 * Generated by: pekkarie
 *
 * Description:
 * Header file generated by Kactus2 for instance "RISCV_CORE" interface "data".
 * This file contains addresses of the memories and registers defined in the memory maps of connected components.
 * Source component: pulp-platform.org:core.cpu:riscv_core:1.0.
*/

#ifndef __RISCV_CORE_DATA_H
#define __RISCV_CORE_DATA_H

/*
 * Instance: data_mem Interface: data
 * Instance base address: 0x100000
 * Source component: pulp-platform.org:core.wrapper:sp_ram_wrap:1.0
 * The defines for the memory map "ram":
*/

#endif /* __RISCV_CORE_DATA_H */

