/*
 * File: instr.h
 * Created on: 13.10.2017
 * Generated by: pekkarie
 *
 * Description:
 * Header file generated by Kactus2 for instance "RISCV_CORE" interface "instr".
 * This file contains addresses of the memories and registers defined in the memory maps of connected components.
 * Source component: pulp-platform.org:core.cpu:riscv_core:1.0.
*/

#ifndef __RISCV_CORE_INSTR_H
#define __RISCV_CORE_INSTR_H

#endif /* __RISCV_CORE_INSTR_H */

